In [48]:
import napari
import os
import numpy as np
import copy
from scipy.spatial import distance, KDTree
from napari import layers

import napari_autoscape as na
import ezomero

In [53]:
host = 'omero-int.biotec.tu-dresden.de'
user = 'johamuel'
group = 'Grapin-Botton lab'
port = 4064
secure = True

conn = ezomero.connect(host=host, user=user, port=port, secure=secure)

In [2]:
from multiview_stitcher.fusion import fuse
from napari_stitcher import StitcherQWidget

In [3]:
viewer = napari.Viewer()

In [4]:
root = r'E:\Data\BiAPoL\Microwells\20250512\20250512_well1_BF_3Zplanes_full_1'
n_images = 20

chosen_indeces = np.unique(np.random.randint(0, len(os.listdir(root)), n_images))
files_to_chose = np.array(os.listdir(root))

viewer.layers.clear()
for idx, file in enumerate(files_to_chose):
    layer = viewer.open(os.path.join(root, file), plugin='napari-autoscape', downsample=16)[0]

for layer in viewer.layers:
    layer.data = layer.data[0]

In [ ]:
well_grid = viewer.layers['Well grid']
image_fused = viewer.layers['fused :: default_channel']

for well in well_grid.data:
    # crop image_fused to well
    
    break

In [ ]:
well_grid = viewer.layers['Well grid']
image_fused = viewer.layers['fused :: default_channel']

for idx, shape in enumerate(well_grid.data):

    row = well_grid.features['row'][idx]
    col = well_grid.features['col'][idx]

    # shape in pixel coordinates
    shape_px = (shape - image_fused.translate) / image_fused.scale
    limits = np.stack([
        np.min(shape_px, axis=0),
        np.max(shape_px, axis=0)
    ]).astype(int)[:, 1:]

    crop = image_fused.data[0][0,
        limits[0, 0] : limits[1, 0],
        limits[0, 1] : limits[1, 1],
    ]

    # translate_crop = image_fused.translate[1:] + limits[0, :] * image_fused.scale[1:]
    # layer = viewer.add_image(crop,
    #      translate=translate_crop,
    #      scale=image_fused.scale[1:],
    #      name='crop'
    #      )
    # layer.bounding_box.visible = True
    # break


In [47]:
row

0

In [40]:
well_grid.features

,row,column
0,0,0
1,0,1
2,0,2
3,0,3
4,0,4
...,...,...
891,31,23
892,31,24
893,31,25
894,31,26


In [12]:
image_fused.translate

array([    0.        ,  3950.60791148, 30328.39341148])

In [13]:
image_fused.scale

array([1.        , 0.32430006, 0.32430006])

In [16]:
(shape - image_fused.translate) / image_fused.scale

array([[    0.        ,  1514.38826377, 21570.54542731],
       [    0.        ,  1247.34379201, 21724.72362731],
       [    0.        ,   980.29932025, 21570.54542731],
       [    0.        ,   980.29932025, 21262.18902731],
       [    0.        ,  1247.34379201, 21108.01082731],
       [    0.        ,  1514.38826377, 21262.18902731]])