In [1]:
import napari
import os
import numpy as np

In [2]:
viewer = napari.Viewer()

In [3]:
root = r'E:\Data\BiAPoL\Microwells\20250512\20250512_well1_BF_3Zplanes_full_1'
n_images = 20

chosen_indeces = np.unique(np.random.randint(0, len(os.listdir(root)), n_images))
files_to_chose = np.array(os.listdir(root))[chosen_indeces]

viewer.layers.clear()
for idx, file in enumerate(files_to_chose):
    viewer.open(os.path.join(root, file), plugin='napari-autoscape', downsample=8)

RuntimeError: Failed to import command at 'napari_autoscape._reader:napari_get_reader': name 'napari' is not defined

In [22]:
points_layer = viewer.layers['Points']

In [24]:
points_layer.scale

array([10.        ,  0.32430006,  0.32430006])

In [25]:
points_layer.data

array([[   194.507     ,  16229.04874277, 115701.14572872],
       [   194.507     ,  19860.76573651, 114817.75510862],
       [   194.507     ,  17505.05741625, 108634.02076793],
       [   192.507     ,  33492.56189849, 101104.4586673 ],
       [   192.507     ,  24436.18856605,  98934.49749189],
       [   192.507     ,  17316.94366648,  96097.30796211]])

In [27]:
positions = points_layer.data * points_layer.scale
positions


array([[ 1945.07      ,  5263.08153253, 37521.88886909],
       [ 1945.07      ,  6440.84758303, 37235.40523518],
       [ 1945.07      ,  5676.89122595, 35230.01979785],
       [ 1925.07      , 10861.63993953, 32788.18233294],
       [ 1925.07      ,  7924.65749569, 32084.46378667],
       [ 1925.07      ,  5615.88592501, 31164.36304293]])

In [28]:
locations_layer = viewer.layers['SCAPE_fields']
query_points = np.stack([np.mean(loc, axis=0) for loc in locations_layer.data])
query_points

array([[ 1925.0701, 11144.016 , 30874.148 ],
       [ 1925.0701, 10878.416 , 30874.148 ],
       [ 1925.0701, 10612.815 , 30874.148 ],
       ...,
       [ 1925.0701,  5035.216 , 37514.15  ],
       [ 1925.0701,  4769.6157, 37514.15  ],
       [ 1925.0701,  4504.0156, 37514.15  ]], dtype=float32)

In [29]:
order = 2
poly_model = fit_polynomial_surface(positions, order)
poly_model

<function __main__.fit_polynomial_surface.<locals>.poly_model(x, y)>

In [30]:
z_pred = poly_model(query_points[:, 2], query_points[:, 1])

In [31]:
points_fitted = np.stack([
    z_pred,
    query_points[:, 1],
    query_points[:, 2],
]).T

In [32]:
points_fitted.shape

(676, 3)

In [33]:
viewer.add_points(points_fitted, name='fitted_points', size=50, face_color='orange')

<Points layer 'fitted_points' at 0x18d8f67e210>